version: 2
jobs:
  build:
    docker:
      - image: python:3

    steps:
      - checkout
      - run:
          name: OS packages
          command: apt-get update && apt-get install -y libgmp3-dev
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Install locally
          command: pip install -U .
      - run:
          name: girepo help
          command: girepo --help
      - run:
          name: girepo rough
          command: girepo rough angular react vue
      - run:
          name: girepo strict
          command: girepo strict angular/angular facebook/react vuejs/vue --headless --desc star
