version: 2
jobs:
  build:
    docker:
      - image: python:3.7
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: OS packages
          command: apt-get update
      - run:
          name: Install dependencies
          command: |
            python -m venv venv || virtualenv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
            pip install -U .
      - run:
          name: girepo help
          command: |
            . venv/bin/activate
            girepo --help
      - run:
          name: girepo rough
          command: |
            . venv/bin/activate
            girepo rough angular react vue
      - run:
          name: girepo strict
          command: |
            . venv/bin/activate
            girepo strict angular/angular facebook/react vuejs/vue --headless --desc star
      - store_artifacts:
          path: test-reports
          destination: test-reports
