version: 2
jobs:
  build:
    docker:
      - image: python:3.5
    working_directory: ~/girepo-test
    steps:
      - checkout
      - run:
          name: OS packages
          command: apt-get update
      - run:
          name: Install dependencies
          command: |
            python -m venv venv || virtualenv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Install girepo locally
          command: pip install -U .
      - run:
          name: girepo help
          command: girepo --help
      - run:
          name: girepo rough
          command: girepo rough angular react vue
      - run:
          name: girepo strict
          command: girepo strict angular/angular facebook/react vuejs/vue --headless --desc star
